apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: grpc-test-server
  name: grpc-test-server
  namespace: lab
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: grpc-test-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-test-client
  name: grpc-test-client
  namespace: lab
spec:
  selector:
    matchLabels:
      app: grpc-test-client
  template:
    metadata:
      labels:
        app: grpc-test-client
    spec:
      containers:
        - image: quay.io/jakekeeys/grpc-lb-test:latest
          imagePullPolicy: Always
          name: grpc-test-client
          args:
            - client
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_BIND
              value: ":8080"
            - name: GRPC_SERVER
              value: "grpc-test-server:8090"
            - name: INTERVAL_MS
              value: "100"
          resources:
            requests:
              memory: 25Mi
            limits:
              memory: 50Mi