apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: grpc-test-server
  name: grpc-test-server
  namespace: lab
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 8090
    targetPort: 8090
  selector:
    app: grpc-test-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-test-server
  name: grpc-test-server
  namespace: lab
spec:
  replicas: 5
  selector:
    matchLabels:
      app: grpc-test-server
  template:
    metadata:
      labels:
        app: grpc-test-server
    spec:
      containers:
      - image: quay.io/jakekeeys/grpc-lb-test:latest
        imagePullPolicy: Always
        name: grpc-test-server
        args:
          - server
        ports:
          - containerPort: 8080
          - containerPort: 8090
        env:
        - name: HTTP_BIND
          value: ":8080"
        - name: GRPC_BIND
          value: ":8090"
        resources:
          requests:
            memory: 25Mi
          limits:
            memory: 50Mi